language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="azblob"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -uy"
   - POST_INSTALL_HOOK="true"
   - PINS="azblob.0.1.0:. azblob-async.0.1.0:."
   - REVDEPS="cohttp-async"
 matrix:
   - DISTRO=centos OCAML_VERSION=4.04
   - DISTRO=fedora OCAML_VERSION=4.04
   - DISTRO=debian-testing OCAML_VERSION=4.05
   - DISTRO=alpine OCAML_VERSION=4.06
   - DISTRO=debian-stable OCAML_VERSION=4.07 DEPOPTS="azblob-async"
   - DISTRO=alpine OCAML_VGERSION=4.08
