name: azblob
description: |
  A trivial Azure Blob Storage client.
  You can get and put Blob on server side dart.
version: 2.0.0
homepage: https://github.com/kkazuo/dart-azblob

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  crypto: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
