name: azblob
description: |
  A trivial Azure Blob Storage client.
  You can get and put Blob on server side dart.
version: 1.0.2
homepage: https://github.com

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  crypto: ^2.1.4

dev_dependencies:
  pedantic: ^1.8.0
  effective_dart: ^1.2.0
  test: ^1.6.0
